/**
 * API reference directory: drives /api-reference/[endpoint] pages.
 *
 * Each entry is a per-endpoint editorial wrapper around the canonical
 * spec already published in /openapi.json. The pages target branded
 * search queries like "tensorfeed routing api" and give agents
 * searching for a specific capability a direct landing page with
 * code samples in three languages plus the MCP tool name.
 *
 * Endpoints are grouped by category for the index page; per-endpoint
 * pages are auto-generated by the [endpoint] dynamic route.
 */

export type EndpointTier = 'free' | 'free-with-token' | 'premium';
export type EndpointCategory =
  | 'news'
  | 'status'
  | 'models'
  | 'routing'
  | 'history'
  | 'forecast'
  | 'agents'
  | 'watches'
  | 'payment'
  | 'agent-brief';

export interface ApiRefParam {
  name: string;
  in: 'query' | 'path' | 'body';
  required?: boolean;
  type: string;
  description: string;
  example?: string;
}

export interface ApiRefMeta {
  /** URL slug used in /api-reference/[endpoint] */
  slug: string;
  /** Display name */
  name: string;
  /** API path */
  path: string;
  /** HTTP method */
  method: 'GET' | 'POST' | 'DELETE';
  /** Tier */
  tier: EndpointTier;
  /** Cost (credits or "Free") */
  cost: string;
  /** Category for grouping */
  category: EndpointCategory;
  /** SEO title (< 60 chars) */
  seoTitle: string;
  /** SEO description (150-160 chars) */
  seoDescription: string;
  /** One-paragraph intro for the page */
  intro: string;
  /** Why an agent calls this */
  whenToUse: string;
  /** Query / path / body parameters */
  params: ApiRefParam[];
  /** Compact example response (will be JSON-stringified by the page) */
  exampleResponse: string;
  /** Python SDK call (multi-line OK, will be in pre block) */
  pythonExample: string;
  /** TypeScript SDK call */
  typescriptExample: string;
  /** MCP tool name for the same call (or null if not exposed via MCP) */
  mcpTool: string | null;
  /** Related endpoint slugs (link from this page to others) */
  relatedSlugs: string[];
  /** FAQPage entries: question + answer */
  faqs: { q: string; a: string }[];
}

export const API_REFERENCE: ApiRefMeta[] = [
  // ── Free: news, status, models ─────────────────────────────────────
  {
    slug: 'news',
    name: 'News',
    path: '/api/news',
    method: 'GET',
    tier: 'free',
    cost: 'Free',
    category: 'news',
    seoTitle: 'TensorFeed News API: Latest AI Headlines, Free, No Auth',
    seoDescription:
      'TensorFeed /api/news returns the latest AI news from 15+ sources updated every 10 minutes. Free, no auth, JSON response. Filter by category, limit results. Built for agents.',
    intro:
      'The /api/news endpoint returns the latest AI news articles aggregated from 15+ sources including Anthropic, OpenAI, Google, TechCrunch, The Verge, Hacker News, and more. Updated every 10 minutes via a Cloudflare Worker cron. No authentication required, generous limits, and a stable JSON shape designed for agent consumption.',
    whenToUse:
      'When your agent needs to know what is happening in AI right now. The free tier is sufficient for most cases; if you need full-text search with relevance scoring, see /api/premium/news/search.',
    params: [
      { name: 'category', in: 'query', type: 'string', description: 'Filter by category (e.g. research, tools, anthropic, openai)' },
      { name: 'limit', in: 'query', type: 'integer', description: 'Number of articles (default 50, max 200)', example: '20' },
    ],
    exampleResponse: `{
  "ok": true,
  "source": "tensorfeed.ai",
  "updated": "2026-04-27T18:00:00Z",
  "count": 20,
  "articles": [
    {
      "id": "abc123",
      "title": "Anthropic ships Claude Opus 4.7",
      "url": "https://anthropic.com/...",
      "source": "Anthropic Blog",
      "sourceDomain": "anthropic.com",
      "snippet": "New flagship model with 1M context window...",
      "categories": ["Anthropic", "Models"],
      "publishedAt": "2026-04-17T15:00:00Z",
      "fetchedAt": "2026-04-17T15:10:00Z"
    }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
result = tf.news(category="research", limit=20)
for article in result["articles"]:
    print(article["title"], "-", article["source"])`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const result = await tf.news({ category: 'research', limit: 20 });
for (const a of result.articles) {
  console.log(\`\${a.title} - \${a.source}\`);
}`,
    mcpTool: 'get_ai_news',
    relatedSlugs: ['premium-news-search', 'whats-new', 'today'],
    faqs: [
      {
        q: 'How often is the news endpoint updated?',
        a: 'Every 10 minutes. A Cloudflare Worker cron polls all 15+ RSS sources and writes the deduplicated article list to KV.',
      },
      {
        q: 'Is the news endpoint rate-limited?',
        a: 'No explicit rate limit on the free tier. We rely on Cloudflare\'s built-in DDoS protection. Identify your agent with a descriptive User-Agent header.',
      },
      {
        q: 'Can I filter by source instead of category?',
        a: 'Not directly via /api/news. The premium /api/premium/news/search endpoint supports a provider filter that matches against source name and source domain.',
      },
    ],
  },
  {
    slug: 'status',
    name: 'Service Status',
    path: '/api/status',
    method: 'GET',
    tier: 'free',
    cost: 'Free',
    category: 'status',
    seoTitle: 'TensorFeed Status API: Live AI Service Status, Free',
    seoDescription:
      'TensorFeed /api/status returns real-time operational status for Claude, OpenAI, Gemini, Mistral, Cohere, Replicate, HuggingFace, and more. Polled every 5 minutes. Free, no auth.',
    intro:
      'The /api/status endpoint returns the live operational status of major AI services. Polled every 5 minutes by a Cloudflare Worker cron that hits each provider\'s status page directly. Status values are normalized to operational, degraded, down, or unknown for easy programmatic consumption.',
    whenToUse:
      'When your agent needs to know whether a specific AI service is up before routing a request. Pair with /api/premium/routing to automatically avoid down providers.',
    params: [],
    exampleResponse: `{
  "ok": true,
  "source": "tensorfeed.ai",
  "checked": "2026-04-27T18:00:00Z",
  "services": [
    {
      "name": "Anthropic",
      "provider": "anthropic",
      "status": "operational",
      "statusPageUrl": "https://status.anthropic.com",
      "components": [{ "name": "API", "status": "operational" }],
      "lastChecked": "2026-04-27T17:55:00Z"
    }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
status = tf.status()
for s in status["services"]:
    if s["status"] != "operational":
        print(f"{s['name']} is {s['status']}")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const { services } = await tf.status();
const incidents = services.filter(s => s.status !== 'operational');
console.log(\`\${incidents.length} services with issues\`);`,
    mcpTool: 'get_ai_status',
    relatedSlugs: ['is-down', 'premium-status-uptime', 'incidents'],
    faqs: [
      {
        q: 'How does TensorFeed determine service status?',
        a: 'A Cloudflare Worker cron polls each provider\'s status page (Atlassian Statuspage JSON or HTML banner parsing) every 5 minutes. We normalize to operational, degraded, down, or unknown for consistent agent consumption.',
      },
      {
        q: 'Which AI services does the status endpoint cover?',
        a: 'Anthropic (Claude), OpenAI (ChatGPT, API), Google (Gemini), Mistral, Cohere, Replicate, HuggingFace, Perplexity, Microsoft Copilot, and Midjourney. The list is in worker/src/sources.ts and grows as we add providers.',
      },
      {
        q: 'How accurate is the status data?',
        a: 'The data is as accurate as each provider\'s own status page. We do not run independent probes against the actual APIs. If a provider\'s status page is wrong, our reported status will be wrong too.',
      },
    ],
  },
  {
    slug: 'models',
    name: 'Models',
    path: '/api/models',
    method: 'GET',
    tier: 'free',
    cost: 'Free',
    category: 'models',
    seoTitle: 'TensorFeed Models API: AI Model Pricing, Specs, Free',
    seoDescription:
      'TensorFeed /api/models returns AI model pricing, context windows, capabilities, and tiers across all major providers. Updated daily. Free, no auth.',
    intro:
      'The /api/models endpoint returns the complete AI model catalog: per-model input price, output price, context window, capabilities, tier (flagship / mid / budget), and release date. The catalog is updated daily by merging community-maintained sources (LiteLLM) with our own curated baseline.',
    whenToUse:
      'When your agent needs the canonical pricing or specs for a model. For ranked recommendations based on a task and budget, use /api/premium/routing instead.',
    params: [],
    exampleResponse: `{
  "ok": true,
  "source": "tensorfeed.ai",
  "lastUpdated": "2026-04-27",
  "providers": [
    {
      "id": "anthropic",
      "name": "Anthropic",
      "models": [
        {
          "id": "claude-opus-4-7",
          "name": "Claude Opus 4.7",
          "inputPrice": 15,
          "outputPrice": 75,
          "contextWindow": 1000000,
          "capabilities": ["text", "vision", "tool-use", "code"],
          "tier": "flagship"
        }
      ]
    }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
catalog = tf.models()
for provider in catalog["providers"]:
    for m in provider["models"]:
        print(f"{m['name']}: \${m['inputPrice']}/\${m['outputPrice']} per 1M")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const catalog = await tf.models();
const flagship = catalog.providers
  .flatMap(p => p.models.filter(m => m.tier === 'flagship'));`,
    mcpTool: 'get_model_pricing',
    relatedSlugs: ['benchmarks', 'premium-routing', 'premium-cost-projection', 'premium-compare-models'],
    faqs: [
      {
        q: 'How often is the models catalog updated?',
        a: 'Daily, at 7am UTC. We merge LiteLLM\'s community-maintained pricing with our own curated baseline so new models from major providers land within a day.',
      },
      {
        q: 'Are the prices in /api/models always current?',
        a: 'Yes for the major providers we track. Edge cases (new providers, regional variants, volume discounts beyond the published rate cards) may lag. For production budgeting use /api/premium/cost/projection which projects against the live catalog.',
      },
      {
        q: 'What is the difference between /api/models and /api/pricing?',
        a: 'Same data. /api/pricing is a legacy alias kept for backwards compatibility. New integrations should use /api/models.',
      },
    ],
  },
  {
    slug: 'benchmarks',
    name: 'Benchmarks',
    path: '/api/benchmarks',
    method: 'GET',
    tier: 'free',
    cost: 'Free',
    category: 'models',
    seoTitle: 'TensorFeed Benchmarks API: AI Model Scores, Free',
    seoDescription:
      'TensorFeed /api/benchmarks returns AI model benchmark scores: SWE-bench, MMLU-Pro, HumanEval, GPQA, MATH. Updated weekly. Free, no auth.',
    intro:
      'The /api/benchmarks endpoint returns benchmark scores for major AI models across SWE-bench (real software engineering tasks), MMLU-Pro (general reasoning), HumanEval (code generation), GPQA Diamond (graduate science), and MATH (competition math). Updated weekly as new scores publish.',
    whenToUse:
      'When your agent needs to compare model capability on a specific dimension. For per-benchmark leaderboard views see /benchmarks/[name]; for time-series of one model on one benchmark, use /api/premium/history/benchmarks/series.',
    params: [],
    exampleResponse: `{
  "ok": true,
  "lastUpdated": "2026-04-24",
  "benchmarks": [
    { "id": "swe_bench", "name": "SWE-bench", "description": "Real GitHub issue resolution", "maxScore": 100 }
  ],
  "models": [
    {
      "model": "Claude Opus 4.7",
      "provider": "Anthropic",
      "scores": { "swe_bench": 65.4, "mmlu_pro": 93.8, "human_eval": 96.2 }
    }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
b = tf.benchmarks()
# Sort models by SWE-bench desc
ranked = sorted(b["models"], key=lambda m: m["scores"].get("swe_bench", 0), reverse=True)`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const { models } = await tf.benchmarks();
const top = models
  .filter(m => m.scores.swe_bench)
  .sort((a, b) => b.scores.swe_bench - a.scores.swe_bench);`,
    mcpTool: null,
    relatedSlugs: ['models', 'premium-routing', 'premium-benchmark-series', 'premium-compare-models'],
    faqs: [
      {
        q: 'Where do the benchmark scores come from?',
        a: 'Published scores from each benchmark\'s official leaderboard plus, where applicable, vendor-published numbers verified against the test methodology. We do not run independent benchmark evaluations.',
      },
      {
        q: 'How current are the benchmark scores?',
        a: 'Updated weekly via the daily catalog cron. New model launches typically land within a few days of public score publication.',
      },
    ],
  },

  // ── Free with token: payment / usage ─────────────────────────────
  {
    slug: 'payment-info',
    name: 'Payment Info',
    path: '/api/payment/info',
    method: 'GET',
    tier: 'free',
    cost: 'Free',
    category: 'payment',
    seoTitle: 'TensorFeed Payment Info API: Wallet, Pricing, USDC on Base',
    seoDescription:
      'TensorFeed /api/payment/info returns the wallet address, pricing tiers, supported flows, and verification metadata for the agent payments tier. Free, no auth.',
    intro:
      'The /api/payment/info endpoint returns everything an agent needs to validate before sending USDC: wallet address, asset (USDC contract on Base), credit-per-USD pricing, volume bundles, both supported flows (credits and x402 fallback), and the operator legal entity (Pizza Robot Studios LLC, California). Cross-check the wallet address here against the other three published locations before sending funds.',
    whenToUse:
      'Always call this before initiating a credit purchase. The response is the canonical source of truth for the wallet address and current pricing.',
    params: [],
    exampleResponse: `{
  "ok": true,
  "operator": {
    "legal_entity": "Pizza Robot Studios LLC",
    "jurisdiction": "California, USA",
    "contact": "evan@tensorfeed.ai"
  },
  "wallet": {
    "address": "0x549c82e6bfc54bdae9a2073744cbc2af5d1fc6d1",
    "currency": "USDC",
    "network": "base",
    "contract": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "decimals": 6
  },
  "pricing": { "base_rate": "50 credits per $1 USDC ($0.02 per credit)", ... }
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
info = tf.payment_info()
print("Send USDC to:", info["wallet"]["address"])
print("Operator:", info["operator"]["legal_entity"])`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const info = await tf.paymentInfo();
console.log('Wallet:', info.wallet.address);`,
    mcpTool: null,
    relatedSlugs: ['payment-buy-credits', 'payment-confirm', 'payment-balance'],
    faqs: [
      {
        q: 'How do I verify the TensorFeed wallet address?',
        a: 'Cross-check the address across four published locations: /api/payment/info (this endpoint), /llms.txt, the GitHub README at github.com/RipperMercs/tensorfeed, and the @tensorfeed bio on X. If any of the four disagree, do not send funds.',
      },
      {
        q: 'What is the operator legal entity?',
        a: 'Pizza Robot Studios LLC, a California limited liability company. They are the legal counterparty for premium-tier purchases, refunds, and disputes per the Terms of Service at /terms.',
      },
    ],
  },
  {
    slug: 'payment-buy-credits',
    name: 'Buy Credits',
    path: '/api/payment/buy-credits',
    method: 'POST',
    tier: 'free',
    cost: 'Free',
    category: 'payment',
    seoTitle: 'TensorFeed Buy Credits API: Quote a USDC Payment',
    seoDescription:
      'TensorFeed /api/payment/buy-credits returns a 30-min payment quote: wallet, memo, credits, expiry. POST amount_usd to start the credit purchase flow. Free, no auth.',
    intro:
      'POST to this endpoint with an amount_usd to receive a payment quote: the wallet address to send USDC to, a memo (optional but recommended), the credit amount you will receive, and a 30-minute expiry. Send the USDC, then call /api/payment/confirm with the tx_hash and memo.',
    whenToUse:
      'Step 1 of the credits-first payment flow. Use this for any agent that will make repeat premium calls; the latency cost is paid once on the credits purchase rather than per-call.',
    params: [
      { name: 'amount_usd', in: 'body', required: true, type: 'number', description: 'USD value to purchase. Min 0.5, max 10000. Volume discounts at $5 (10%), $30 (25%), $200 (40%).' },
    ],
    exampleResponse: `{
  "ok": true,
  "wallet": "0x549c82e6bfc54bdae9a2073744cbc2af5d1fc6d1",
  "memo": "tf-eb13b1a17c6811d6",
  "amount_usd": 1.0,
  "credits": 50,
  "currency": "USDC",
  "network": "base",
  "expires_at": "2026-04-27T18:30:00Z",
  "ttl_seconds": 1800,
  "next_step": "Send 1.0 USDC on Base to 0x549..., then POST /api/payment/confirm with tx_hash and memo."
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
quote = tf.buy_credits(amount_usd=1.0)
print(f"Send {quote['amount_usd']} USDC to {quote['wallet']}")
print(f"Memo: {quote['memo']}")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const quote = await tf.buyCredits({ amountUsd: 1.0 });
console.log(\`Send \${quote.amount_usd} USDC to \${quote.wallet}\`);`,
    mcpTool: null,
    relatedSlugs: ['payment-info', 'payment-confirm', 'payment-balance'],
    faqs: [
      {
        q: 'How much USDC should I send?',
        a: 'Send exactly the amount_usd from the quote. The on-chain verification compares the received amount against the quoted amount within $0.01; if it matches, you get the quoted credits including any volume discount. If you send more or less, credits are calculated from the actual amount at the base rate.',
      },
      {
        q: 'How long is the quote valid?',
        a: '30 minutes. After expiry, the quote is unusable and you must request a new one. The /api/payment/confirm call without a nonce uses the actual tx amount at base rate, so a refresh is rarely necessary.',
      },
    ],
  },
  {
    slug: 'payment-confirm',
    name: 'Confirm Payment',
    path: '/api/payment/confirm',
    method: 'POST',
    tier: 'free',
    cost: 'Free',
    category: 'payment',
    seoTitle: 'TensorFeed Confirm Payment API: Verify USDC, Mint Token',
    seoDescription:
      'TensorFeed /api/payment/confirm verifies a USDC transaction on Base mainnet and returns a bearer token. POST tx_hash and optional nonce. Free, no auth.',
    intro:
      'POST to this endpoint with the tx_hash of your USDC transfer on Base. The Worker reads the transaction receipt from the Base RPC, verifies the recipient and amount, and returns a tf_live_ bearer token tied to your credits. Replay protection is enforced: each tx hash can mint credits exactly once.',
    whenToUse:
      'Step 2 of the credits-first payment flow, after the USDC has confirmed on Base. Typically called within 30 minutes of /api/payment/buy-credits with the same memo for volume-discount accuracy.',
    params: [
      { name: 'tx_hash', in: 'body', required: true, type: 'string', description: '0x-prefixed Base mainnet transaction hash' },
      { name: 'nonce', in: 'body', type: 'string', description: 'Optional memo from buy-credits to apply volume discount' },
    ],
    exampleResponse: `{
  "ok": true,
  "token": "tf_live_eb0d0155...",
  "credits": 50,
  "balance": 50,
  "tx_amount_usd": 1.0,
  "rate": "base"
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed()
result = tf.confirm(tx_hash="0x13bc...", nonce="tf-eb13b1a17c6811d6")
# Token is auto-stored on tf
rec = tf.routing(task="code")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed();
const result = await tf.confirm({ txHash: '0x13bc...', nonce: 'tf-...' });
// tf.token is auto-set
const rec = await tf.routing({ task: 'code' });`,
    mcpTool: null,
    relatedSlugs: ['payment-info', 'payment-buy-credits', 'payment-balance', 'payment-usage'],
    faqs: [
      {
        q: 'How long does on-chain verification take?',
        a: 'The Worker calls eth_getTransactionReceipt on a Base mainnet RPC. Once the tx is confirmed (a few seconds after broadcast), verification completes in 200-500ms. We verify the USDC Transfer event log, recipient address, and amount before minting credits.',
      },
      {
        q: 'What if I submit the same tx_hash twice?',
        a: 'Rejected. Replay protection is permanent: every used tx hash is recorded under pay:tx:{txHash} in our KV store with no TTL. The second confirm call returns ok: false with reason: tx_already_claimed.',
      },
    ],
  },
  {
    slug: 'payment-balance',
    name: 'Token Balance',
    path: '/api/payment/balance',
    method: 'GET',
    tier: 'free-with-token',
    cost: 'Free with bearer token',
    category: 'payment',
    seoTitle: 'TensorFeed Balance API: Check Credits Remaining',
    seoDescription:
      'TensorFeed /api/payment/balance returns the credit balance for the current bearer token. Authorization: Bearer tf_live_... required. Free.',
    intro:
      'The /api/payment/balance endpoint returns the current credit balance, total purchased, creation timestamp, and last-used timestamp for the bearer token. Useful for agents that want to monitor their own spend or top up before exhaustion.',
    whenToUse:
      'Periodically during a long-running agent session, or before initiating a high-credit-cost workload. Cheap to call (no credits charged).',
    params: [],
    exampleResponse: `{
  "ok": true,
  "balance": 49,
  "created": "2026-04-27T15:00:00Z",
  "last_used": "2026-04-27T17:30:00Z",
  "total_purchased": 50
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
print(tf.balance())  # {"balance": 49, ...}`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const { balance } = await tf.balance();
if (balance < 5) { /* top up */ }`,
    mcpTool: 'get_account_balance',
    relatedSlugs: ['payment-usage', 'payment-buy-credits'],
    faqs: [
      {
        q: 'How do I check my balance without spending a credit?',
        a: 'Just call /api/payment/balance with your bearer token. The endpoint is free; no credits are decremented for the call.',
      },
      {
        q: 'Do credits expire?',
        a: 'No. Per the Terms of Service, credits do not expire. They remain spendable until consumed. Tokens are durable: store them like API keys.',
      },
    ],
  },
  {
    slug: 'payment-usage',
    name: 'Token Usage History',
    path: '/api/payment/usage',
    method: 'GET',
    tier: 'free-with-token',
    cost: 'Free with bearer token',
    category: 'payment',
    seoTitle: 'TensorFeed Usage API: Per-Token API Call History',
    seoDescription:
      'TensorFeed /api/payment/usage returns the last 100 calls aggregated by endpoint for the current bearer token. Authorization required. Free.',
    intro:
      'The /api/payment/usage endpoint returns your token\'s call history: the last 100 premium API calls aggregated by endpoint with per-endpoint counts and total credits spent, plus the 25 most recent entries. Powers the human-facing /account dashboard but useful for any agent monitoring its own spend.',
    whenToUse:
      'Anytime you need to audit per-endpoint usage for a token, monitor spend velocity, or render a usage dashboard.',
    params: [],
    exampleResponse: `{
  "ok": true,
  "token_balance": 47,
  "total_calls": 3,
  "total_credits_spent": 3,
  "by_endpoint": {
    "/api/premium/routing": { "calls": 2, "credits": 2, "last_seen": "2026-04-27T17:30:00Z" }
  },
  "recent": [
    { "endpoint": "/api/premium/routing", "credits": 1, "at": "2026-04-27T17:30:00Z" }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
usage = tf.usage()
for endpoint, info in usage["by_endpoint"].items():
    print(f"{endpoint}: {info['calls']} calls, {info['credits']} credits")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const usage = await tf.usage();
console.log(\`\${usage.total_calls} calls, \${usage.total_credits_spent} credits\`);`,
    mcpTool: 'get_account_usage',
    relatedSlugs: ['payment-balance', 'payment-info'],
    faqs: [
      {
        q: 'How far back does the usage history go?',
        a: 'The ring buffer holds the last 100 calls per token. Older calls roll off. For longer history, the daily site-wide rollup at /api/admin/usage is auth-gated and tracks per-endpoint volume across all tokens.',
      },
      {
        q: 'Is there a UI for the usage data?',
        a: 'Yes. /account is a noindex private dashboard where humans can paste their token to see balance + usage history. Token is stored in sessionStorage only, never localStorage.',
      },
    ],
  },

  // ── Premium: routing ─────────────────────────────────────────────
  {
    slug: 'premium-routing',
    name: 'Routing Recommendations',
    path: '/api/premium/routing',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'routing',
    seoTitle: 'TensorFeed Routing API: Top-N AI Model Recommendations',
    seoDescription:
      'TensorFeed /api/premium/routing returns top-N ranked AI models for a task with composite-score breakdown across quality, availability, cost, latency. 1 credit per call.',
    intro:
      'The premium routing endpoint synthesizes live pricing, benchmark scores, and provider status into a single composite score per model and returns the top-N ranked recommendations for your task. Custom weights via query params let you tune the tradeoff (quality-heavy, cost-heavy, etc.) without re-deriving the scoring yourself.',
    whenToUse:
      'When your agent needs to pick a model for a task and wants the decision to consider quality, cost, and provider status simultaneously. Faster and more accurate than maintaining your own scoring code.',
    params: [
      { name: 'task', in: 'query', type: 'string', description: 'Task family: code, reasoning, creative, general (default general)' },
      { name: 'budget', in: 'query', type: 'number', description: 'Max blended USD per 1M tokens' },
      { name: 'min_quality', in: 'query', type: 'number', description: 'Minimum quality score in [0, 1]' },
      { name: 'top_n', in: 'query', type: 'integer', description: 'How many models to return (1-10, default 5)' },
      { name: 'w_quality', in: 'query', type: 'number', description: 'Custom quality weight (defaults to 0.4)' },
      { name: 'w_cost', in: 'query', type: 'number', description: 'Custom cost weight (defaults to 0.2)' },
    ],
    exampleResponse: `{
  "ok": true,
  "task": "code",
  "weights": { "quality": 0.4, "availability": 0.3, "cost": 0.2, "latency": 0.1 },
  "recommendations": [
    {
      "rank": 1,
      "model": { "name": "Claude Opus 4.7", "provider": "anthropic" },
      "pricing": { "input": 15, "output": 75 },
      "status": "operational",
      "composite_score": 0.87,
      "components": { "quality": 0.94, "availability": 1.0, "cost": 0.65, "latency": 0.5 }
    }
  ],
  "billing": { "credits_charged": 1, "credits_remaining": 49 }
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
rec = tf.routing(task="code", budget=5.0, top_n=3)
for r in rec["recommendations"]:
    print(f"#{r['rank']}: {r['model']['name']} ({r['composite_score']:.2f})")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const rec = await tf.routing({ task: 'code', budget: 5.0, topN: 3 });`,
    mcpTool: 'premium_routing',
    relatedSlugs: ['preview-routing', 'premium-cost-projection', 'premium-compare-models'],
    faqs: [
      {
        q: 'How is the composite score computed?',
        a: 'The composite is a weighted sum of four sub-scores in [0, 1]: quality (per-task benchmark blend), availability (provider status), cost (normalized blended price across the candidate set), latency (placeholder 0.5 in v1). Default weights: 40% quality, 30% availability, 20% cost, 10% latency. Override via w_quality, w_availability, w_cost, w_latency.',
      },
      {
        q: 'How does the quality score change by task?',
        a: 'Code task weights HumanEval (40%) and SWE-bench (40%) plus MMLU-Pro (20%). Reasoning weights GPQA-Diamond (40%) and MATH (40%) plus MMLU-Pro (20%). Creative weights MMLU-Pro (50%) plus HumanEval and MATH (25% each). General is a balanced blend across all five.',
      },
      {
        q: 'What is the difference between /api/premium/routing and /api/preview/routing?',
        a: 'Preview is free, returns the top-1 result with no score breakdown, and is rate-limited to 5 calls per UTC day per IP. Premium returns top-N with full component breakdown, no rate limit, 1 credit per call.',
      },
    ],
  },

  // ── Premium: history series ──────────────────────────────────────
  {
    slug: 'premium-pricing-series',
    name: 'Pricing Series',
    path: '/api/premium/history/pricing/series',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'history',
    seoTitle: 'TensorFeed Pricing Series API: Daily Model Price History',
    seoDescription:
      'TensorFeed /api/premium/history/pricing/series returns daily input/output/blended price points for one model with min/max/delta summary. 1 credit. Up to 90 days back.',
    intro:
      'The pricing series endpoint returns the daily price points for one model across a date range, computed from the daily history snapshots. Each point includes input price, output price, and blended (average). The summary block surfaces first/latest, min/max, percent delta, and a count of detected price changes in the window.',
    whenToUse:
      'When you need to know how a model\'s price has moved over time. For a real-time alert when a price crosses a threshold, use a price watch instead.',
    params: [
      { name: 'model', in: 'query', required: true, type: 'string', description: 'Model id or display name' },
      { name: 'from', in: 'query', type: 'string', description: 'Start date YYYY-MM-DD UTC (default 30 days ago)' },
      { name: 'to', in: 'query', type: 'string', description: 'End date YYYY-MM-DD UTC (default today)' },
    ],
    exampleResponse: `{
  "ok": true,
  "model": "Claude Opus 4.7",
  "provider": "Anthropic",
  "range": { "from": "2026-04-01", "to": "2026-04-27", "days": 27 },
  "points": [
    { "date": "2026-04-01", "input": 18, "output": 90, "blended": 54 },
    { "date": "2026-04-27", "input": 12, "output": 60, "blended": 36 }
  ],
  "summary": {
    "delta_pct_blended": -33.33,
    "changes_detected": 2,
    "min_blended": 36, "max_blended": 54
  }
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
series = tf.pricing_series(model="Claude Opus 4.7")
print(f"Price moved {series['summary']['delta_pct_blended']}%")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const s = await tf.pricingSeries({ model: 'Claude Opus 4.7' });`,
    mcpTool: 'pricing_series',
    relatedSlugs: ['premium-history-compare', 'premium-forecast', 'premium-watches'],
    faqs: [
      {
        q: 'How far back can I query?',
        a: 'Up to 90 days. The default window is 30 days back from today. Snapshots before our Phase 0 capture started are not available; the dataset compounds as we go.',
      },
      {
        q: 'What does "changes_detected" count?',
        a: 'The number of distinct days within the window where the input or output price changed from the previous day. A model whose price moved twice in 30 days reports changes_detected: 2.',
      },
    ],
  },
  {
    slug: 'premium-benchmark-series',
    name: 'Benchmark Series',
    path: '/api/premium/history/benchmarks/series',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'history',
    seoTitle: 'TensorFeed Benchmark Series API: Model Score Over Time',
    seoDescription:
      'TensorFeed /api/premium/history/benchmarks/series returns score evolution for one benchmark on one model with delta in percentage points. 1 credit. 90 days max.',
    intro:
      'The benchmark series endpoint returns the daily score evolution for a single benchmark on a single model. Useful for tracking whether a model is improving (provider released a fine-tune), regressing (provider downgraded the API endpoint to a smaller model), or holding steady.',
    whenToUse:
      'When a research agent needs to track a benchmark trajectory. For a snapshot leaderboard at a single date, see /benchmarks/[name].',
    params: [
      { name: 'model', in: 'query', required: true, type: 'string', description: 'Model id or display name' },
      { name: 'benchmark', in: 'query', required: true, type: 'string', description: 'Benchmark key (swe_bench, mmlu_pro, gpqa_diamond, math, human_eval)' },
      { name: 'from', in: 'query', type: 'string', description: 'Start date YYYY-MM-DD UTC' },
      { name: 'to', in: 'query', type: 'string', description: 'End date YYYY-MM-DD UTC' },
    ],
    exampleResponse: `{
  "ok": true,
  "model": "Claude Opus 4.7",
  "benchmark": "swe_bench",
  "points": [
    { "date": "2026-04-01", "score": 70.0 },
    { "date": "2026-04-27", "score": 73.4 }
  ],
  "summary": { "first": { "score": 70.0 }, "latest": { "score": 73.4 }, "delta_pp": 3.4 }
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
s = tf.benchmark_series(model="Claude Opus 4.7", benchmark="swe_bench")
print(f"SWE-bench moved {s['summary']['delta_pp']} pp")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const s = await tf.benchmarkSeries({ model: 'Claude Opus 4.7', benchmark: 'swe_bench' });`,
    mcpTool: 'benchmark_series',
    relatedSlugs: ['benchmarks', 'premium-forecast', 'premium-history-compare'],
    faqs: [
      {
        q: 'Why would a benchmark score change over time on the same model?',
        a: 'Three common reasons: provider released a fine-tune or new system prompt and updated the score, the test methodology changed (e.g. SWE-bench Verified subset got new tasks), or the score was recalculated against a different harness. Tracking the trajectory surfaces these changes.',
      },
    ],
  },
  {
    slug: 'premium-status-uptime',
    name: 'Uptime Rollup',
    path: '/api/premium/history/status/uptime',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'history',
    seoTitle: 'TensorFeed Uptime API: Daily Provider Status Rollup',
    seoDescription:
      'TensorFeed /api/premium/history/status/uptime returns operational/degraded/down day counts and uptime % for a provider over up to 90 days. 1 credit per call.',
    intro:
      'The uptime endpoint returns a daily rollup of one provider\'s status over a date range: operational day count, degraded day count, down day count, an SLA-style uptime percentage, and an incident_days list. Degraded days count as half-credit for the uptime calc; missing-data days are excluded from the denominator so a brief gap in our capture does not skew the result.',
    whenToUse:
      'When you need an SLA-grade uptime report on a specific provider, or when you want to surface provider reliability in a procurement decision.',
    params: [
      { name: 'provider', in: 'query', required: true, type: 'string', description: 'Provider name (anthropic, openai, google, etc.)' },
      { name: 'from', in: 'query', type: 'string', description: 'Start date YYYY-MM-DD UTC' },
      { name: 'to', in: 'query', type: 'string', description: 'End date YYYY-MM-DD UTC' },
    ],
    exampleResponse: `{
  "ok": true,
  "provider": "anthropic",
  "days_total": 27,
  "days_with_data": 27,
  "days_operational": 24,
  "days_degraded": 2,
  "days_down": 1,
  "uptime_pct": 92.59,
  "incident_days": [
    { "date": "2026-04-09", "status": "degraded" },
    { "date": "2026-04-17", "status": "down" }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
uptime = tf.status_uptime(provider="anthropic")
print(f"{uptime['uptime_pct']}% uptime")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const u = await tf.statusUptime({ provider: 'anthropic' });`,
    mcpTool: 'status_uptime',
    relatedSlugs: ['status', 'incidents', 'premium-watches'],
    faqs: [
      {
        q: 'How is uptime % calculated?',
        a: '(days_operational + days_degraded * 0.5) / days_with_data * 100. Down days count zero. Days where we did not capture status data (any reason) are excluded from the denominator so brief outages in our own monitoring do not penalize the provider.',
      },
    ],
  },
  {
    slug: 'premium-history-compare',
    name: 'Snapshot Diff',
    path: '/api/premium/history/compare',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'history',
    seoTitle: 'TensorFeed History Compare API: Diff Two Snapshots',
    seoDescription:
      'TensorFeed /api/premium/history/compare diffs two daily snapshots: added, removed, and changed entries with deltas. Type pricing or benchmarks. 1 credit.',
    intro:
      'The snapshot diff endpoint compares two daily history snapshots and returns the added, removed, and changed entries with deltas. Useful for "what changed in the AI pricing market between March 1 and April 1" or "which model benchmark scores moved" queries that would otherwise require multiple calls and client-side joining.',
    whenToUse:
      'When you need a structured diff between two specific dates rather than a continuous time series. For continuous evolution use the series endpoints.',
    params: [
      { name: 'from', in: 'query', required: true, type: 'string', description: 'Earlier snapshot date YYYY-MM-DD' },
      { name: 'to', in: 'query', required: true, type: 'string', description: 'Later snapshot date YYYY-MM-DD' },
      { name: 'type', in: 'query', type: 'string', description: 'pricing or benchmarks (default pricing)' },
    ],
    exampleResponse: `{
  "ok": true,
  "type": "pricing",
  "from_date": "2026-04-01", "to_date": "2026-04-27",
  "added": [{ "model": "Opus 4.7", "provider": "Anthropic", "inputPrice": 15, "outputPrice": 75 }],
  "removed": [],
  "changed": [
    { "model": "GPT-5.5", "field": "inputPrice", "from": 12, "to": 10, "delta_pct": -16.67 }
  ],
  "unchanged_count": 8
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
diff = tf.history_compare(from_date="2026-04-01", to_date="2026-04-27")
print(f"{len(diff['changed'])} changes, {len(diff['added'])} new models")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const diff = await tf.historyCompare({ from: '2026-04-01', to: '2026-04-27' });`,
    mcpTool: 'history_compare',
    relatedSlugs: ['premium-pricing-series', 'premium-benchmark-series', 'whats-new'],
    faqs: [],
  },

  // ── Premium: agents ──────────────────────────────────────────────
  {
    slug: 'premium-agents-directory',
    name: 'Enriched Agents Directory',
    path: '/api/premium/agents/directory',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'agents',
    seoTitle: 'TensorFeed Premium Agents Directory: Enriched AI Tools',
    seoDescription:
      'TensorFeed /api/premium/agents/directory: AI agents catalog joined with live status, recent news, agent traffic, flagship pricing, and a 0-100 trending score. 1 credit.',
    intro:
      'The premium agents directory takes the static AI agents catalog and joins it with live signals: provider status, recent news mentions for that provider, agent traffic attribution from our bot signature tracking, and flagship pricing from /api/models. Each entry gets a derived 0-100 trending score that blends recency-weighted news count, agent traffic, and live status.',
    whenToUse:
      'When your agent needs a ranked, filtered shortlist of AI agents/tools rather than the raw catalog. Server-side filter and sort means agents pull a tight list in one call instead of stitching free endpoints.',
    params: [
      { name: 'category', in: 'query', type: 'string', description: 'Filter to one category (coding, research, general, creative, frameworks)' },
      { name: 'status', in: 'query', type: 'string', description: 'operational, degraded, down, unknown' },
      { name: 'open_source', in: 'query', type: 'boolean', description: 'true for OSS-only, false for closed-only' },
      { name: 'sort', in: 'query', type: 'string', description: 'trending, alphabetical, status, price_low, price_high, news_count (default trending)' },
      { name: 'limit', in: 'query', type: 'integer', description: 'Max records (1-100, default 50)' },
    ],
    exampleResponse: `{
  "ok": true,
  "total": 18, "returned": 5,
  "agents": [
    {
      "id": "claude-code", "name": "Claude Code", "provider": "Anthropic",
      "live_status": "operational", "recent_news_count": 7,
      "agent_traffic_24h": 124, "trending_score": 86
    }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
dir = tf.premium_agents_directory(category="coding", sort="trending", limit=5)`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const d = await tf.premiumAgentsDirectory({ category: 'coding', sort: 'trending' });`,
    mcpTool: 'premium_agents_directory',
    relatedSlugs: ['premium-provider-deepdive', 'premium-news-search'],
    faqs: [
      {
        q: 'How is the trending_score calculated?',
        a: '60% recent news count (capped at 20 articles), 30% agent traffic (capped at 30 hits), 10% live status boost (operational +10, degraded +4, down 0, unknown +6). Range [0, 100].',
      },
    ],
  },
  {
    slug: 'premium-provider-deepdive',
    name: 'Provider Deep-Dive',
    path: '/api/premium/providers/{name}',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'agents',
    seoTitle: 'TensorFeed Provider Deep-Dive API: Full Profile in One Call',
    seoDescription:
      'TensorFeed /api/premium/providers/{name} aggregates live status, all models with pricing + benchmarks joined, recent news, and agent traffic in one paid call. 1 credit.',
    intro:
      'The provider deep-dive endpoint returns one complete profile per call: live status with components, all of the provider\'s models in tier order with pricing and benchmark scores joined, recent news mentions, and agent traffic. Aggregation over four free endpoints in a single paid request.',
    whenToUse:
      'When your agent is evaluating one provider in depth and would otherwise stitch /api/status, /api/models, /api/benchmarks, and /api/news client-side. Saves four round-trips and a non-trivial join.',
    params: [
      { name: 'name', in: 'path', required: true, type: 'string', description: 'Provider id or display name (case-insensitive)' },
    ],
    exampleResponse: `{
  "ok": true,
  "provider": { "id": "anthropic", "name": "Anthropic" },
  "status": { "state": "operational", "status_page_url": "..." },
  "models": [
    { "id": "opus-4-7", "name": "Claude Opus 4.7", "tier": "flagship",
      "pricing": { "input": 15, "output": 75, "blended": 45 },
      "benchmark_scores": { "swe_bench": 73.4, "mmlu_pro": 88.5 } }
  ],
  "recent_news_count": 12, "agent_traffic_24h": 124
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
profile = tf.provider_deepdive("anthropic")
for m in profile["models"]:
    print(m["name"], m["pricing"]["blended"])`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const profile = await tf.providerDeepDive('anthropic');`,
    mcpTool: 'provider_deepdive',
    relatedSlugs: ['premium-agents-directory', 'premium-compare-models', 'providers'],
    faqs: [],
  },
  {
    slug: 'premium-compare-models',
    name: 'Compare Models',
    path: '/api/premium/compare/models',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'models',
    seoTitle: 'TensorFeed Compare Models API: Side-By-Side AI Comparison',
    seoDescription:
      'TensorFeed /api/premium/compare/models compares 2-5 AI models side-by-side with normalized benchmarks, pricing, status, and rankings. 1 credit per call.',
    intro:
      'The compare-models endpoint returns a side-by-side block per model: pricing, benchmarks normalized to a union-of-keys with null for missing scores (so downstream code never crashes on undefined), provider live status, capabilities, context window, and recent news. Plus three rankings: cheapest blended, most context, and a per-benchmark leaderboard.',
    whenToUse:
      'When picking between 2-5 specific models for a workload. Returns ready-to-rank data without the agent having to write the join itself.',
    params: [
      { name: 'ids', in: 'query', required: true, type: 'string', description: 'Comma-separated list of 2-5 model ids or names' },
    ],
    exampleResponse: `{
  "ok": true,
  "benchmark_keys": ["mmlu_pro", "swe_bench"],
  "models": [
    {
      "matched": true, "name": "Claude Opus 4.7", "provider": "Anthropic",
      "pricing": { "blended": 45 },
      "benchmarks": { "swe_bench": 73.4, "mmlu_pro": 88.5 }
    }
  ],
  "rankings": {
    "cheapest_blended": [{ "name": "Gemini 3", "blended": 14 }],
    "by_benchmark": { "swe_bench": [{ "name": "Claude Opus 4.7", "score": 73.4 }] }
  }
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
c = tf.compare_models(ids=["Claude Opus 4.7", "GPT-5.5", "Gemini 2.5 Pro"])`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const c = await tf.compareModels({ ids: ['Claude Opus 4.7', 'GPT-5.5'] });`,
    mcpTool: 'compare_models',
    relatedSlugs: ['premium-routing', 'premium-cost-projection', 'premium-provider-deepdive'],
    faqs: [
      {
        q: 'Why are benchmarks normalized to union-of-keys with null?',
        a: 'So downstream code can iterate the keys without TypeErrors on undefined values. If GPT-5.5 has no MMLU-Pro score and Opus does, both show mmlu_pro in the benchmarks object — Opus with the score, GPT-5.5 with null. Predictable shape, no special-casing.',
      },
    ],
  },

  // ── Premium: news / brief / forecast / cost ──────────────────────
  {
    slug: 'premium-news-search',
    name: 'News Search',
    path: '/api/premium/news/search',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'news',
    seoTitle: 'TensorFeed News Search API: Full-Text AI News Search',
    seoDescription:
      'TensorFeed /api/premium/news/search: full-text search over the AI news corpus with relevance scoring, date/provider/category filters, recency boost. 1 credit.',
    intro:
      'The news search endpoint runs a full-text search over the article corpus with relevance scoring (term hits in title weighted 3x over snippet 1x, plus a recency boost). Filters: date range, provider substring match, category. Stop words are stripped. Each result includes title, url, source, snippet, published_at, relevance score, and the matched query terms.',
    whenToUse:
      'When an agent needs targeted search ("what did Anthropic publish in March?", "any news mentioning agent payments?"). For a curated daily summary instead of search, see whats-new.',
    params: [
      { name: 'q', in: 'query', type: 'string', description: 'Free-text query. Omit to browse latest filtered articles.' },
      { name: 'from', in: 'query', type: 'string', description: 'Start date YYYY-MM-DD UTC' },
      { name: 'to', in: 'query', type: 'string', description: 'End date YYYY-MM-DD UTC' },
      { name: 'provider', in: 'query', type: 'string', description: 'Substring match against source name and domain' },
      { name: 'category', in: 'query', type: 'string', description: 'Substring match against article categories' },
      { name: 'limit', in: 'query', type: 'integer', description: 'Max results (1-100, default 25)' },
    ],
    exampleResponse: `{
  "ok": true,
  "query": "opus pricing",
  "matched": 12, "returned": 12,
  "results": [
    {
      "title": "Anthropic ships Claude Opus 4.7", "url": "...",
      "source": "Anthropic Blog", "published_at": "2026-04-27T12:00:00Z",
      "relevance": 0.85, "matched_terms": ["opus"]
    }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
r = tf.news_search(q="agent payments", from_date="2026-04-01")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const r = await tf.newsSearch({ q: 'agent payments' });`,
    mcpTool: 'news_search',
    relatedSlugs: ['news', 'whats-new', 'premium-history-compare'],
    faqs: [
      {
        q: 'How does the relevance score work?',
        a: 'A token in the title contributes 3 points; a token in the snippet contributes 1 point. The total is normalized by query length so longer queries do not automatically out-score shorter ones (caps at 0.7). Then a recency boost in [0, 0.3] is added based on how recent the article is in the matched window. Final score is in [0, 1].',
      },
    ],
  },
  {
    slug: 'whats-new',
    name: 'What\'s New (Agent Brief)',
    path: '/api/premium/whats-new',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'agent-brief',
    seoTitle: 'TensorFeed What\'s New API: Agent Morning Brief',
    seoDescription:
      'TensorFeed /api/premium/whats-new: pricing changes + new models + status incidents + top news from the last 1-7 days in one paid call. The agent boot-up endpoint.',
    intro:
      'The "what\'s new" endpoint is the single call an agent makes when it boots up. Returns a curated 1-7 day window across pricing changes (input/output deltas), new and removed models, status incidents that started or resolved in the period, current operational counts, and the top news headlines. Replaces the loop of "GET news, GET status, GET models, diff yesterday\'s snapshot" that agents would otherwise write themselves.',
    whenToUse:
      'On agent boot-up. The right cadence is once per session for short-lived agents, once per day for long-running agents.',
    params: [
      { name: 'days', in: 'query', type: 'integer', description: 'Window in days (1-7, default 1)' },
      { name: 'news_limit', in: 'query', type: 'integer', description: 'Max news headlines (1-25, default 10)' },
    ],
    exampleResponse: `{
  "ok": true,
  "window": { "from": "2026-04-26T...", "to": "2026-04-27T...", "days": 1 },
  "summary": { "total_pricing_changes": 2, "new_models": 1, "incidents": 1, "news_articles": 8 },
  "pricing": {
    "changes": [{ "model": "Claude Opus 4.7", "field": "inputPrice", "from": 15, "to": 12, "delta_pct": -20 }]
  },
  "status": { "currently_operational": 8, "currently_degraded": 0, "currently_down": 0 },
  "news": [{ "title": "...", "url": "...", "published_at": "..." }]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
brief = tf.whats_new(days=1, news_limit=10)
for c in brief["pricing"]["changes"]:
    print(f"{c['model']} {c['field']}: {c['from']} -> {c['to']}")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const brief = await tf.whatsNew({ days: 1 });`,
    mcpTool: 'whats_new',
    relatedSlugs: ['premium-history-compare', 'premium-news-search', 'premium-watches'],
    faqs: [],
  },
  {
    slug: 'premium-cost-projection',
    name: 'Cost Projection',
    path: '/api/premium/cost/projection',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'models',
    seoTitle: 'TensorFeed Cost Projection API: AI Workload Cost Estimator',
    seoDescription:
      'TensorFeed /api/premium/cost/projection projects a token-usage workload across 1-10 models with daily/weekly/monthly/yearly totals and cheapest-monthly ranking. 1 credit.',
    intro:
      'The cost projection endpoint takes your expected daily input + output token volume and projects the cost across up to 10 models. Returns daily/weekly/monthly/yearly totals per model plus a ranking by cheapest monthly. Pure compute on live pricing.',
    whenToUse:
      'When you need to budget for a workload across multiple model candidates. Useful for FinOps reporting or for an agent picking the cost-optimal model.',
    params: [
      { name: 'model', in: 'query', required: true, type: 'string', description: 'Comma-separated 1-10 model ids or names' },
      { name: 'input_tokens_per_day', in: 'query', required: true, type: 'number', description: 'Expected daily input volume' },
      { name: 'output_tokens_per_day', in: 'query', required: true, type: 'number', description: 'Expected daily output volume' },
      { name: 'horizon', in: 'query', type: 'string', description: 'Primary horizon: daily, weekly, monthly (default), yearly' },
    ],
    exampleResponse: `{
  "ok": true,
  "workload": { "input_tokens_per_day": 1000000, "output_tokens_per_day": 500000 },
  "projections": [
    {
      "model": "Claude Opus 4.7", "matched": true,
      "rates": { "input_per_1m": 15, "output_per_1m": 75 },
      "daily": { "total": 52.5 },
      "monthly_total": 1575
    }
  ],
  "ranked_cheapest_monthly": [
    { "model": "Gemini 3", "monthly_total": 525 }
  ]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
p = tf.cost_projection(
    models=["Claude Opus 4.7", "GPT-5.5"],
    input_tokens_per_day=1_000_000,
    output_tokens_per_day=500_000,
)`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const p = await tf.costProjection({
  models: ['Claude Opus 4.7'],
  inputTokensPerDay: 1_000_000,
  outputTokensPerDay: 500_000,
});`,
    mcpTool: 'cost_projection',
    relatedSlugs: ['premium-routing', 'premium-compare-models', 'models'],
    faqs: [],
  },
  {
    slug: 'premium-forecast',
    name: 'Forecast',
    path: '/api/premium/forecast',
    method: 'GET',
    tier: 'premium',
    cost: '1 credit',
    category: 'forecast',
    seoTitle: 'TensorFeed Forecast API: Price and Benchmark Projection',
    seoDescription:
      'TensorFeed /api/premium/forecast: linear-regression forecast for AI model price or benchmark with 95% prediction interval and confidence label. 1 credit.',
    intro:
      'The forecast endpoint runs a linear least-squares fit over 7-90 days of historical price or benchmark data and projects 1-30 days forward with a 95% prediction interval. The response includes a confidence score and label (low/medium/high) so agents can ignore low-signal forecasts. Includes explicit "statistical inference, not a guarantee" disclaimers.',
    whenToUse:
      'When you need a planning estimate for where a price or benchmark is headed. Treat low-confidence forecasts as no signal rather than a directional call.',
    params: [
      { name: 'target', in: 'query', required: true, type: 'string', description: 'price or benchmark' },
      { name: 'model', in: 'query', required: true, type: 'string', description: 'Model id or display name' },
      { name: 'field', in: 'query', type: 'string', description: 'For price target: inputPrice, outputPrice, blended' },
      { name: 'benchmark', in: 'query', type: 'string', description: 'For benchmark target: swe_bench, mmlu_pro, etc.' },
      { name: 'lookback', in: 'query', type: 'integer', description: 'Days of history to fit on (7-90, default 30)' },
      { name: 'horizon', in: 'query', type: 'integer', description: 'Days to project forward (1-30, default 7)' },
    ],
    exampleResponse: `{
  "ok": true,
  "target": "price", "model": "Claude Opus 4.7", "field": "blended",
  "current_value": 36,
  "trend": { "slope_per_day": -0.31, "r_squared": 0.78 },
  "confidence": { "score": 0.7, "label": "high" },
  "forecast": [
    { "date": "2026-04-28", "predicted": 35.69, "lower": 34.2, "upper": 37.18 }
  ],
  "notes": ["Statistical inference, not a guarantee..."]
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
f = tf.forecast(target="price", model="Claude Opus 4.7", field="blended")
print(f"Confidence: {f['confidence']['label']}")`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
const f = await tf.forecast({ target: 'price', model: 'Claude Opus 4.7', field: 'blended' });`,
    mcpTool: 'forecast',
    relatedSlugs: ['premium-pricing-series', 'premium-benchmark-series'],
    faqs: [],
  },

  // ── Premium: watches ─────────────────────────────────────────────
  {
    slug: 'premium-watches',
    name: 'Webhook Watches',
    path: '/api/premium/watches',
    method: 'POST',
    tier: 'premium',
    cost: '1 credit per registration',
    category: 'watches',
    seoTitle: 'TensorFeed Watches API: Webhook Alerts on Price/Status/Digest',
    seoDescription:
      'TensorFeed /api/premium/watches registers a webhook watch on price changes, status transitions, or scheduled digests. HMAC-signed POST delivery. 1 credit.',
    intro:
      'The watches endpoint registers a webhook watch. Three types: price (fires on threshold cross or any change), status (fires on provider state transitions), and digest (fires on a daily or weekly cadence with a curated summary regardless of activity). Each watch lives 90 days, fires up to 100 times by default, and delivers HMAC-SHA256 signed POST requests to your callback URL.',
    whenToUse:
      'When your agent needs realtime notifications instead of polling. Price watches are the canonical "alert me when X drops below Y" pattern; digest watches are set-and-forget periodic summaries.',
    params: [
      { name: 'spec', in: 'body', required: true, type: 'object', description: 'Watch type discriminator: { type: price | status | digest, ... }' },
      { name: 'callback_url', in: 'body', required: true, type: 'string', description: 'HTTPS URL for signed POST delivery' },
      { name: 'secret', in: 'body', type: 'string', description: 'Optional HMAC shared secret (recommended)' },
      { name: 'fire_cap', in: 'body', type: 'integer', description: 'Max fires before auto-disable (1-1000, default 100)' },
    ],
    exampleResponse: `{
  "ok": true,
  "watch": {
    "id": "wat_a1b2c3d4e5f60718a9b0c1d2",
    "spec": { "type": "price", "model": "Claude Opus 4.7", "field": "blended", "op": "lt", "threshold": 30 },
    "callback_url": "https://agent.example.com/hook",
    "expires_at": "2026-07-26T18:00:00Z",
    "fire_count": 0, "fire_cap": 100, "status": "active"
  }
}`,
    pythonExample: `from tensorfeed import TensorFeed

tf = TensorFeed(token="tf_live_...")
tf.create_watch(
    spec={"type": "price", "model": "Claude Opus 4.7", "field": "blended", "op": "lt", "threshold": 30},
    callback_url="https://agent.example.com/hook",
    secret="any-shared-secret",
)`,
    typescriptExample: `import { TensorFeed } from 'tensorfeed';

const tf = new TensorFeed({ token: 'tf_live_...' });
await tf.createWatch({
  spec: { type: 'price', model: 'Claude Opus 4.7', field: 'blended', op: 'lt', threshold: 30 },
  callbackUrl: 'https://agent.example.com/hook',
  secret: 'shared-secret',
});`,
    mcpTool: 'create_price_watch',
    relatedSlugs: ['premium-pricing-series', 'premium-status-uptime', 'whats-new'],
    faqs: [
      {
        q: 'How are webhooks signed?',
        a: 'Each delivery includes an X-TensorFeed-Signature header containing sha256=<hex> where the hex is HMAC-SHA256 of the request body using the secret you provided at registration. Verify with crypto.timingSafeEqual to prevent timing-side-channel attacks.',
      },
      {
        q: 'What if my callback URL is down when the watch fires?',
        a: 'The fire is logged with last_delivery_status reflecting the HTTP status (or null on network error) and fire_count is incremented. We do not retry. If reliability matters, point the callback URL at a queue or pub/sub.',
      },
    ],
  },
];

export function getApiRefBySlug(slug: string): ApiRefMeta | null {
  return API_REFERENCE.find(e => e.slug === slug) ?? null;
}

export function getAllApiRefSlugs(): string[] {
  return API_REFERENCE.map(e => e.slug);
}

export function getApiRefsByCategory(): Record<EndpointCategory, ApiRefMeta[]> {
  const grouped: Partial<Record<EndpointCategory, ApiRefMeta[]>> = {};
  for (const e of API_REFERENCE) {
    if (!grouped[e.category]) grouped[e.category] = [];
    grouped[e.category]!.push(e);
  }
  return grouped as Record<EndpointCategory, ApiRefMeta[]>;
}
